### ISSUE TITLE
It might be necessary to allow the user to scroll to the bottom of the screen.

### ISSUE THREAD

**Issue by ZoneTwelve** [CMUH-CMAX/cmax_frontend#9]
It might be necessary to allow the user to scroll to the bottom of the screen.

![Screenshot 2024-02-15 at 11 09 37 PM](https://github.com/CMUH-CMAX/cmax_frontend/assets/20425883/1a7f3f8d-9df8-4c47-954e-ad2fafd2089f)

_Originally posted by @ZoneTwelve in https://github.com/CMUH-CMAX/cmax_frontend/issues/5#issuecomment-1946289982_

**Comment by jackshinshin** [comment]
I'm not sure about how the issue should be solved. Do you mean that only the buttons on the screen should be scrolled to the bottom?

**Comment by ZoneTwelve** [comment]
> I'm not sure about how the issue should be solved. Do you mean that only the buttons on the screen should be scrolled to the bottom?

The button is currently covered by the navigation bar, which may impact the user experience.

**Comment by jackshinshin** [comment]
How did you find that? The layout remains normal on my end, which means there are no covered buttons. I use iphone 14 pro max for layout reference.

**Comment by ZoneTwelve** [comment]
Fixed @ https://github.com/CMUH-CMAX/cmax_frontend/pull/5
